### ISSUE TITLE
关于作为依赖引用问题

### ISSUE THREAD

**Issue by iceBear67** [cnlimiter/onebot-client#6]
首先非常感谢作者愿意分享这样一个项目。但是，似乎 README 里指向 QuickStart 和文档的超链接是原地转圈，且 README 也没有提供 maven 系依赖管理器的依赖坐标或者仓库，唯一有点头绪的似乎是 Github Release 上发布的 jar 包。

翻阅 build.gradle, 偶然发现您的工件托管在 Nova Repository 上，然而里面似乎没有 0.4.0. 最后，JitPack 上的 0.4.0 也构建失败了。

总之，我想问的是，onebot-client 是只能手动下载 JAR 包在本地仓库导入吗？或者，Nova 上的 `0.3.9.2` 是否可以正常使用？

期待您的回复.

**Comment by cnlimiter** [comment]
请在repositories中添加
`maven { url = "https://maven.nova-committee.cn/releases" }`
然后请在dependencies中使用
`implementation ("cn.evole.onebot:OneBot-Client:0.4.0")`
