### ISSUE TITLE
OneBot 11 鉴权没有正确实现

### ISSUE THREAD

**Issue by iceBear67** [cnlimiter/onebot-client#7]
https://github.com/cnlimiter/onebot-client/blob/9abf6b5050fcca1ca75f47618bb46d34e677da33/src/main/java/cn/evole/onebot/client/OneBotClient.java#L60-L62

根据 [ob 11](https://github.com/botuniverse/onebot-11/blob/master/communication/authorization.md#http-%E5%92%8C%E6%AD%A3%E5%90%91-websocket)：
![image](https://github.com/user-attachments/assets/9b7a8df4-9d58-4263-acfb-c575e2e1352d)

我比较好奇这个库的作者有没有用 onebot 11 测试过能不能用

**Comment by iceBear67** [comment]
我的用例:
```java
var cfg = new BotConfig("wss://SERVER:443/" or "ws://SERVER" or "wss://SERVER" or "ws://SERVER/" ,"TOKEN",QQL,true,false,true,500,"string");
        oneBot = OneBotClient.create(cfg);
        oneBot.open();
```

bot config 初始化参考自 https://github.com/Nova-Committee/McBot/blob/fabric/fabric/src/main/java/cn/evole/mods/mcbot/config/BotConfig.java

始终卡在 403 Forbidden, 是我看了假的 ob11？

#  Workaround

使用 `wss://server/?access_token=`

**Comment by cnlimiter** [comment]
已修复
